---
title: "PM566 Final Project"
author: "Lin Wang"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---
<br>

This is my PM566 Final Project website.

<br>

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = FALSE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")

library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(ggplot2)
library(DT)
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```


```{r load-data}
source(knitr::purl("Midterm.rmd", quiet=FALSE))
```

## Scatterplots

```{r plot1, class.source="code-r-small"}
p1 <- ggplot(covid_ca1)+
  geom_point(mapping = aes(x = date, y = newcases, color = month))+
  ggtitle("New cases in California by month")+
  theme_classic()
ggplotly(p1)
```

## Maps

##  {.tabset}

### Covid cases across California today

```{r plot4, class.source="code-r-small"}
ggplotly(p2)
```

### Covid deaths across California today

```{r plot5, class.source="code-r-small"}
ggplotly(p3)
```

## Bar Chart

##  {.tabset}

### Counties in CA with top ten cases

```{r plot6, class.source="code-r-small"}
top_10_cases %>%
  plot_ly(x = ~reorder(county,-cases), y =~cases, type = 'bar') %>%
  layout(title = "Counties in CA with top ten cases",
         xaxis = list(title ="County"))
```

### Counties in CA with top ten deaths

```{r plot7, class.source="code-r-small"}
top_10_deaths %>%
  plot_ly(x = ~reorder(county,-deaths), y =~deaths, type = 'bar') %>%
  layout(title = "Counties in CA with top ten deaths",
         xaxis = list(title ="County"))
```